export const CATEGORY_WEIGHTS: Record<string, number> = {
  technical: 1.2,
  analytical: 1.1,
  creative: 1.15,
  social: 1.0,
  independent: 0.9,
  university: 1.0,
  professional: 0.95,
  practical: 1.05,
}

export const VOCATIONAL_QUESTIONS = [
  {
    question: "¿Cuál es tu principal interés?",
    answers: [
      { text: "Trabajar con números y datos", category: "analytical", value: 3 },
      { text: "Crear cosas nuevas y diseñar", category: "creative", value: 3 },
      { text: "Ayudar a otras personas", category: "social", value: 3 },
      { text: "Trabajar con tecnología", category: "technical", value: 3 },
    ],
  },
  {
    question: "¿Cómo prefieres trabajar?",
    answers: [
      { text: "En equipo colaborativo", category: "social", value: 2 },
      { text: "De forma independiente", category: "independent", value: 2 },
      { text: "En un ambiente estructurado", category: "analytical", value: 2 },
      { text: "En un ambiente flexible y creativo", category: "creative", value: 2 },
    ],
  },
  {
    question: "¿Qué tipo de problemas te gusta resolver?",
    answers: [
      { text: "Problemas lógicos y matemáticos", category: "analytical", value: 3 },
      { text: "Problemas creativos y artísticos", category: "creative", value: 3 },
      { text: "Problemas relacionados con personas", category: "social", value: 3 },
      { text: "Problemas técnicos y prácticos", category: "technical", value: 3 },
    ],
  },
  {
    question: "¿Cuál es tu nivel de educación deseado?",
    answers: [
      { text: "Carrera universitaria (4+ años)", category: "university", value: 3 },
      { text: "Carrera técnica (2-3 años)", category: "technical", value: 3 },
      { text: "Certificación profesional", category: "professional", value: 3 },
      { text: "Formación práctica en el trabajo", category: "practical", value: 2 },
    ],
  },
  {
    question: "¿Qué ambiente laboral prefieres?",
    answers: [
      { text: "Oficina o laboratorio", category: "analytical", value: 2 },
      { text: "Aire libre o en movimiento", category: "practical", value: 2 },
      { text: "Interacción directa con clientes", category: "social", value: 2 },
      { text: "Espacio creativo y moderno", category: "creative", value: 2 },
    ],
  },
  {
    question: "¿Cuál es tu fortaleza principal?",
    answers: [
      { text: "Análisis y pensamiento crítico", category: "analytical", value: 3 },
      { text: "Creatividad e innovación", category: "creative", value: 3 },
      { text: "Comunicación y empatía", category: "social", value: 3 },
      { text: "Habilidades técnicas y manuales", category: "technical", value: 3 },
    ],
  },
  {
    question: "¿Qué te motiva más en una carrera?",
    answers: [
      { text: "Estabilidad económica", category: "analytical", value: 2 },
      { text: "Expresión personal y creatividad", category: "creative", value: 2 },
      { text: "Impacto social positivo", category: "social", value: 2 },
      { text: "Innovación y tecnología", category: "technical", value: 2 },
    ],
  },
  {
    question: "¿Cómo te ves en 10 años?",
    answers: [
      { text: "En una posición de liderazgo", category: "analytical", value: 2 },
      { text: "Trabajando en proyectos creativos", category: "creative", value: 2 },
      { text: "Haciendo una diferencia en la comunidad", category: "social", value: 2 },
      { text: "Siendo experto en mi campo técnico", category: "technical", value: 2 },
    ],
  },
  {
    question: "¿Qué tipo de actividades te entretienen más?",
    answers: [
      { text: "Investigar y aprender cosas nuevas", category: "analytical", value: 3 },
      { text: "Experimentar y probar ideas nuevas", category: "creative", value: 3 },
      { text: "Conversar y conectar con personas", category: "social", value: 3 },
      { text: "Construir y reparar cosas", category: "technical", value: 3 },
    ],
  },
  {
    question: "¿Cómo reaccionas ante un conflicto en el trabajo?",
    answers: [
      { text: "Analizo la situación objetivamente", category: "analytical", value: 2 },
      { text: "Busco soluciones creativas", category: "creative", value: 2 },
      { text: "Intento mediar y entender a todos", category: "social", value: 2 },
      { text: "Enfoco en resolver el problema práctico", category: "technical", value: 2 },
    ],
  },
  {
    question: "¿Qué características valoras en un trabajo ideal?",
    answers: [
      { text: "Precisión y resultados medibles", category: "analytical", value: 2 },
      { text: "Libertad y expresión", category: "creative", value: 2 },
      { text: "Colaboración y apoyo mutuo", category: "social", value: 2 },
      { text: "Desafíos técnicos constantes", category: "technical", value: 2 },
    ],
  },
  {
    question: "¿Cómo prefieres aprender nuevas habilidades?",
    answers: [
      { text: "Mediante teoría y estudio formal", category: "analytical", value: 3 },
      { text: "Mediante prueba y error", category: "creative", value: 3 },
      { text: "Mediante mentoría y enseñanza de otros", category: "social", value: 3 },
      { text: "Mediante práctica hands-on", category: "technical", value: 3 },
    ],
  },
  {
    question: "¿Qué tipo de dinero te importa más?",
    answers: [
      { text: "Un salario seguro y predecible", category: "analytical", value: 2 },
      { text: "Ingresos variables pero con potencial alto", category: "creative", value: 2 },
      { text: "Que sea justo según el valor que aporto", category: "social", value: 2 },
      { text: "Que sea competitivo en mi industria", category: "technical", value: 2 },
    ],
  },
  {
    question: "¿Cuál es tu relación con la tecnología?",
    answers: [
      { text: "La uso para analizar e interpretar datos", category: "analytical", value: 2 },
      { text: "La uso para expresar mis ideas", category: "creative", value: 2 },
      { text: "La uso para conectar con otros", category: "social", value: 2 },
      { text: "Me fascina entender cómo funciona", category: "technical", value: 3 },
    ],
  },
  {
    question: "¿Cómo manejas la presión y los plazos?",
    answers: [
      { text: "Planificando meticulosamente", category: "analytical", value: 2 },
      { text: "Adaptándome sobre la marcha", category: "creative", value: 2 },
      { text: "Pidiendo apoyo del equipo", category: "social", value: 2 },
      { text: "Enfocándome en la eficiencia", category: "technical", value: 2 },
    ],
  },
  {
    question: "¿Qué tipo de cliente o población prefieres atender?",
    answers: [
      { text: "Empresas e instituciones grandes", category: "analytical", value: 2 },
      { text: "Emprendedores y startups innovadoras", category: "creative", value: 2 },
      { text: "Comunidades y personas vulnerables", category: "social", value: 3 },
      { text: "Sectores tecnológicos", category: "technical", value: 2 },
    ],
  },
  {
    question: "¿Cómo prefieres comunicarte?",
    answers: [
      { text: "Mediante reportes y datos documentados", category: "analytical", value: 2 },
      { text: "Mediante presentaciones visuales y creativas", category: "creative", value: 3 },
      { text: "Mediante conversaciones y reuniones", category: "social", value: 3 },
      { text: "Mediante demostraciones prácticas", category: "technical", value: 2 },
    ],
  },
  {
    question: "¿Qué aspecto de un proyecto te entusiasma más?",
    answers: [
      { text: "Planificación y estrategia", category: "analytical", value: 3 },
      { text: "Concepto y diseño", category: "creative", value: 3 },
      { text: "Ejecución y colaboración", category: "social", value: 2 },
      { text: "Implementación y optimización", category: "technical", value: 3 },
    ],
  },
  {
    question: "¿Cómo ves el futuro de tu industria?",
    answers: [
      { text: "Basado en datos e inteligencia artificial", category: "analytical", value: 2 },
      { text: "Transformado por innovación y creatividad", category: "creative", value: 3 },
      { text: "Focado en sustentabilidad y responsabilidad social", category: "social", value: 3 },
      { text: "Revolucionado por nueva tecnología", category: "technical", value: 3 },
    ],
  },
  {
    question: "¿Cuál es tu mayor preocupación laboral?",
    answers: [
      { text: "No poder aplicar mis habilidades analíticas", category: "analytical", value: 2 },
      { text: "Tener un trabajo muy rutinario", category: "creative", value: 3 },
      { text: "Sentirme aislado o sin propósito social", category: "social", value: 3 },
      { text: "Quedar obsoleto con la tecnología", category: "technical", value: 2 },
    ],
  },
  {
    question: "¿Cómo describes tu estilo de liderazgo?",
    answers: [
      { text: "Basado en datos y objetivos claros", category: "analytical", value: 2 },
      { text: "Inspirador e innovador", category: "creative", value: 2 },
      { text: "Inclusivo y empático", category: "social", value: 3 },
      { text: "Resultado-orientado y eficiente", category: "technical", value: 2 },
    ],
  },
  {
    question: "¿Qué tipo de formación continua prefieres?",
    answers: [
      { text: "Certificaciones en análisis y metodologías", category: "analytical", value: 2 },
      { text: "Talleres en arte, diseño y creatividad", category: "creative", value: 3 },
      { text: "Entrenamientos en liderazgo y comunicación", category: "social", value: 3 },
      { text: "Cursos en nuevas tecnologías", category: "technical", value: 3 },
    ],
  },
  {
    question: "¿Cuál es tu visión del éxito profesional?",
    answers: [
      { text: "Ser reconocido como experto en mi campo", category: "analytical", value: 2 },
      { text: "Ver mis creaciones tener impacto", category: "creative", value: 3 },
      { text: "Haber ayudado a muchas personas", category: "social", value: 3 },
      { text: "Haber innovado y solucionado problemas grandes", category: "technical", value: 2 },
    ],
  },
  {
    question: "¿Cómo reaccionas ante un error importante?",
    answers: [
      { text: "Lo analizo para aprender la lección", category: "analytical", value: 2 },
      { text: "Lo veo como oportunidad de mejorar", category: "creative", value: 2 },
      { text: "Busco apoyo del equipo para solucionarlo", category: "social", value: 2 },
      { text: "Me enfoco en la corrección rápida", category: "technical", value: 2 },
    ],
  },
  {
    question: "¿Qué tipo de problemas sociales te importan?",
    answers: [
      { text: "Eficiencia y sostenibilidad de recursos", category: "analytical", value: 2 },
      { text: "Preservar arte y cultura", category: "creative", value: 2 },
      { text: "Reducir desigualdad y pobreza", category: "social", value: 3 },
      { text: "Acceso a tecnología para todos", category: "technical", value: 2 },
    ],
  },
  {
    question: "¿Cómo ves tu relación con el dinero?",
    answers: [
      { text: "Como herramienta de seguridad", category: "analytical", value: 2 },
      { text: "Como medio para vivir libremente", category: "creative", value: 2 },
      { text: "Como responsabilidad social", category: "social", value: 2 },
      { text: "Como resultado de valor generado", category: "technical", value: 2 },
    ],
  },
  {
    question: "¿Cuál es tu mayor motivación diaria?",
    answers: [
      { text: "Resolver problemas complejos", category: "analytical", value: 3 },
      { text: "Crear algo hermoso o único", category: "creative", value: 3 },
      { text: "Hacer que alguien sonría", category: "social", value: 3 },
      { text: "Aprender algo nuevo", category: "technical", value: 3 },
    ],
  },
  {
    question: "¿Cómo te relacionas con los cambios?",
    answers: [
      { text: "Prefiero planificarlos cuidadosamente", category: "analytical", value: 2 },
      { text: "Los amo, me mantienen vivo", category: "creative", value: 3 },
      { text: "Los enfrento con el equipo", category: "social", value: 2 },
      { text: "Me adapto rápidamente", category: "technical", value: 2 },
    ],
  },
  {
    question: "¿Qué significa satisfacción laboral para ti?",
    answers: [
      { text: "Cumplir objetivos y métricas", category: "analytical", value: 2 },
      { text: "Ver mi trabajo y estar orgulloso", category: "creative", value: 3 },
      { text: "Saber que ayudé a alguien", category: "social", value: 3 },
      { text: "Superar desafíos técnicos", category: "technical", value: 2 },
    ],
  },
  {
    question: "¿Cuál es tu área de expertise preferida?",
    answers: [
      { text: "Investigación, estadística y análisis", category: "analytical", value: 3 },
      { text: "Diseño, arte y expresión visual", category: "creative", value: 3 },
      { text: "Educación, salud y desarrollo humano", category: "social", value: 3 },
      { text: "Ingeniería, programación e innovación", category: "technical", value: 3 },
    ],
  },
]

export const CAREERS_DATABASE = [
  {
    name: "Ingeniería en Sistemas",
    type: "Universitaria",
    description:
      "Diseña, desarrolla y mantiene sistemas informáticos y software. Ideal para quienes aman la tecnología y la resolución de problemas complejos.",
    categories: ["technical", "analytical", "university"],
    skills: ["Programación", "Análisis de datos", "Resolución de problemas"],
    salary: "S/ 12,000 - S/ 20,000/mes",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=300&fit=crop",
    universities: ["Universidad Nacional Autónoma", "Instituto Tecnológico", "Universidad Privada"],
    youtubeLink: "dQw4w9WgXcQ",
  },
  {
    name: "Diseño Gráfico",
    type: "Universitaria",
    description:
      "Crea contenido visual para marcas, publicidad y medios. Perfecto para personas creativas con ojo para el detalle.",
    categories: ["creative", "independent"],
    skills: ["Diseño visual", "Software de diseño", "Comunicación visual"],
    salary: "S/ 7,000 - S/ 15,000/mes",
    image: "https://images.unsplash.com/photo-1561070791250-112173e7f9db?w=400&h=300&fit=crop",
    universities: ["Academia de Diseño", "Universidad de Artes", "Instituto Creativo"],
    youtubeLink: "5Nj2C5z4H3s",
  },
  {
    name: "Psicología",
    type: "Universitaria",
    description:
      "Estudia el comportamiento humano y ayuda a las personas a mejorar su bienestar mental. Requiere empatía y habilidades de escucha.",
    categories: ["social", "analytical"],
    skills: ["Empatía", "Análisis", "Comunicación"],
    salary: "S/ 8,500 - S/ 16,500/mes",
    image: "https://images.unsplash.com/photo-1576091160550-112173e7f9db?w=400&h=300&fit=crop",
    universities: ["Universidad de Salud Mental", "Instituto de Psicología", "Universidad Clínica"],
    youtubeLink: "PL6VQZ8lhO5k",
  },
  {
    name: "Administración de Empresas",
    type: "Universitaria",
    description: "Gestiona recursos, finanzas y operaciones de empresas. Ideal para líderes con visión estratégica.",
    categories: ["analytical", "social", "university"],
    skills: ["Gestión", "Liderazgo", "Análisis financiero"],
    salary: "S/ 10,000 - S/ 21,500/mes",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop",
    universities: ["Escuela de Negocios", "Universidad Empresarial", "Instituto de Gestión"],
    youtubeLink: "Hs7lOmDzc0w",
  },
  {
    name: "Técnico en Electrónica",
    type: "Técnica",
    description: "Instala, repara y mantiene equipos electrónicos. Carrera práctica con alta demanda laboral.",
    categories: ["technical", "practical"],
    skills: ["Electrónica", "Reparación", "Mantenimiento"],
    salary: "S/ 6,000 - S/ 11,500/mes",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=300&fit=crop",
    universities: ["Instituto Técnico Electrónico", "Centro de Capacitación", "Escuela Técnica"],
    youtubeLink: "9J0gG2Sv5nY",
  },
  {
    name: "Técnico en Enfermería",
    type: "Técnica",
    description: "Asiste a profesionales de la salud en hospitales y clínicas. Carrera vocacional con impacto social.",
    categories: ["social", "technical", "practical"],
    skills: ["Cuidado del paciente", "Procedimientos médicos", "Empatía"],
    salary: "S/ 5,000 - S/ 9,500/mes",
    image: "https://images.unsplash.com/photo-1576091160550-112173e7f9db?w=400&h=300&fit=crop",
    universities: ["Instituto de Enfermería", "Centro de Salud", "Escuela Médica Técnica"],
    youtubeLink: "K3x5z7J2mNq",
  },
  {
    name: "Técnico en Programación Web",
    type: "Técnica",
    description: "Desarrolla sitios web y aplicaciones. Carrera corta con excelentes oportunidades laborales.",
    categories: ["technical", "creative"],
    skills: ["HTML/CSS", "JavaScript", "Bases de datos"],
    salary: "S/ 7,000 - S/ 15,000/mes",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=300&fit=crop",
    universities: ["Bootcamp de Programación", "Centro de Tecnología", "Instituto Web"],
    youtubeLink: "X7qh2z7gN9k",
  },
  {
    name: "Contador",
    type: "Técnica",
    description: "Gestiona registros financieros y contables de empresas. Carrera estable con demanda constante.",
    categories: ["analytical", "technical"],
    skills: ["Contabilidad", "Análisis financiero", "Atención al detalle"],
    salary: "S/ 6,000 - S/ 12,500/mes",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop",
    universities: ["Escuela de Contabilidad", "Instituto Financiero", "Centro Contable"],
    youtubeLink: "L8k3Z5mP2Qw",
  },
  {
    name: "Consultor de Recursos Humanos",
    type: "Profesional",
    description: "Ayuda a empresas a mejorar su gestión de personal. Requiere habilidades de comunicación y liderazgo.",
    categories: ["social", "analytical"],
    skills: ["Comunicación", "Liderazgo", "Resolución de conflictos"],
    salary: "S/ 8,000 - S/ 18,000/mes",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop",
    universities: ["Instituto de Recursos Humanos", "Centro de Desarrollo Laboral"],
    youtubeLink: "R9W2pLkN3Xo",
  },
  {
    name: "Especialista en Marketing Digital",
    type: "Profesional",
    description:
      "Gestiona campañas de marketing en línea y redes sociales. Carrera moderna con crecimiento exponencial.",
    categories: ["creative", "analytical", "social"],
    skills: ["Marketing", "Análisis de datos", "Redes sociales"],
    salary: "S/ 7,500 - S/ 16,000/mes",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop",
    universities: ["Academia Digital", "Centro de Marketing", "Instituto de Comunicación Digital"],
    youtubeLink: "W4k7V6jL9Es",
  },
  {
    name: "Consultor de Negocios",
    type: "Profesional",
    description:
      "Asesora a empresas en estrategia y mejora operacional. Requiere experiencia y pensamiento estratégico.",
    categories: ["analytical", "social"],
    skills: ["Análisis estratégico", "Comunicación", "Resolución de problemas"],
    salary: "S/ 12,000 - S/ 26,000/mes",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop",
    universities: ["Consultora Global", "Instituto Empresarial"],
    youtubeLink: "A4m9Y5oP1Ts",
  },
  {
    name: "Fotógrafo Profesional",
    type: "Profesional",
    description: "Captura momentos especiales y crea contenido visual. Carrera creativa con flexibilidad laboral.",
    categories: ["creative", "independent"],
    skills: ["Fotografía", "Edición de imágenes", "Composición visual"],
    salary: "S/ 5,000 - S/ 13,000/mes",
    image: "https://images.unsplash.com/photo-1427504494785-cdec0f72afa5?w=400&h=300&fit=crop",
    universities: ["Escuela de Fotografía", "Academia Visual", "Centro de Artes"],
    youtubeLink: "B5n0Z8cQ3Rs",
  },
  {
    name: "Especialista en Ciberseguridad",
    type: "Universitaria",
    description: "Protege sistemas y datos de amenazas digitales. Carrera de alta demanda en la era digital.",
    categories: ["technical", "analytical"],
    skills: ["Seguridad informática", "Análisis de amenazas", "Programación"],
    salary: "S/ 13,000 - S/ 25,000/mes",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=300&fit=crop",
    universities: ["Instituto de Ciberseguridad", "Universidad Tecnológica", "Centro de Seguridad Digital"],
    youtubeLink: "C6o1X9mL2Fv",
  },
  {
    name: "Ingeniero Civil",
    type: "Universitaria",
    description: "Diseña y construye infraestructuras. Carrera con impacto visible en la sociedad.",
    categories: ["analytical", "technical", "practical"],
    skills: ["Diseño estructural", "Cálculos", "Gestión de proyectos"],
    salary: "S/ 10,000 - S/ 20,000/mes",
    image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400&h=300&fit=crop",
    universities: ["Escuela de Ingeniería Civil", "Universidad Constructora", "Instituto de Obras"],
    youtubeLink: "D7p2J3qR8Gw",
  },
  {
    name: "Educador/Profesor",
    type: "Universitaria",
    description: "Enseña y forma a nuevas generaciones. Carrera vocacional con impacto social duradero.",
    categories: ["social", "creative"],
    skills: ["Enseñanza", "Comunicación", "Paciencia"],
    salary: "S/ 5,000 - S/ 11,500/mes",
    image: "https://images.unsplash.com/photo-1427504494785-cdec0f72afa5?w=400&h=300&fit=crop",
    universities: ["Facultad de Educación", "Instituto Pedagógico", "Universidad de Maestría"],
    youtubeLink: "E8q3K4sT9Hx",
  },
]
